---
title: "Dashboard"
subtitle: "Homer"
logo: "logo.png"

header: true
footer: false

theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

services:
  - name: "Hosting"
    icon: "fas fa-server"
    items:

      - name: "Digital Ocean"
        logo: "assets/tools/digitalocean.png"
        subtitle: "Server Hosting"
        url: "https://cloud.digitalocean.com/login"

      - name: "HostPoint"
        logo: "assets/tools/hostpoint.png"
        subtitle: "Domain Hosting"
        url: "https://admin.hostpoint.ch"

      - name: "Synology"
        logo: "assets/tools/synology.png"
        subtitle: "DiskStation"
        url: "https://cloud.larsgerber.ch/"

      - name: "Cloudinary"
        logo: "assets/tools/cloudinary.png"
        subtitle: "Content Delivery Network"
        url: "https://cloudinary.com/users/login"
        
      - name: "MongoDB"
        logo: "assets/tools/mongodb.svg"
        subtitle: "Database"
        url: "https://account.mongodb.com/account/login"

      - name: "Swisscom"
        logo: "assets/tools/swisscom.png"
        subtitle: "Router"
        url: "http://192.168.1.1/#overview"

  - name: "Containers"
    icon: "fab fa-docker"
    items:

      - name: "Nginx Proxy Manager"
        logo: "assets/tools/nginxproxymanager.png"
        subtitle: "Webserver"
        url: "https://admin.larsgerber.ch/"
        
      - name: "Mailcow"
        logo: "assets/tools/mailcow.svg"
        subtitle: "Mailserver"
        url: "https://mail.larsgerber.ch/"

      - name: "Portainer"
        logo: "assets/tools/portainer.svg"
        subtitle: "Container Management"
        url: "https://portainer.larsgerber.ch"

      - name: "PiHole 11"
        logo: "assets/tools/pihole.png"
        subtitle: "Adblocker"
        url: "http://192.168.1.136:8080/admin"

      - name: "Bitwarden"
        logo: "assets/tools/bitwarden.png"
        subtitle: "Password Manager"
        url: "https://bitwarden.larsgerber.ch"

      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Server Metrics"
        url: "https://metrics.larsgerber.ch"
        
      - name: "Umami"
        logo: "assets/tools/umami.png"
        subtitle: "Website Analytics"
        url: "https://analytics.larsgerber.ch"

  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      
      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.svg"
        subtitle: "Dashboard"
        url: "https://status.larsgerber.ch/dashboard"

      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.svg"
        subtitle: "Status Page"
        url: "https://status.larsgerber.ch/status-page"

      - name: "Uptime Robot"
        logo: "assets/tools/uptime-robot.svg"
        subtitle: "Dashboard"
        url: "https://uptimerobot.com/login"

      - name: "Uptime Robot"
        logo: "assets/tools/uptime-robot.svg"
        subtitle: "Status Page"
        url: "https://stats.uptimerobot.com/3Y5j6Img8l"

  - name: "Websites"
    icon: "fas fa-globe-europe"
    items:
      
      - name: "Swiss Gaming Clan"
        logo: "assets/tools/swissgamingclan.png"
        subtitle: "swissgamingclan.ch"
        url: "https://swissgamingclan.ch/"

      - name: "Blog of Lars Gerber"
        logo: "assets/tools/lg.svg"
        subtitle: "blog.larsgerber.ch"
        url: "https://blog.larsgerber.ch/"

  - name: "Applications"
    icon: "fas fa-cloud"
    items:

      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Media Server"
        url: "https://plex.larsgerber.ch"

      - name: "Strapi"
        logo: "assets/tools/strapi.svg"
        subtitle: "Content-Management-System"
        url: "https://strapi.larsgerber.ch/"
