---
title: "Dashboard"
subtitle: "Homer"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "//Hosting"
    icon: "fas fa-server"
    items:

      - name: "Digital Ocean"
        logo: "assets/tools/digitalocean.png"
        subtitle: "Server Hosting"
        url: "https://cloud.digitalocean.com/login"

      - name: "Hetzner Cloud"
        logo: "assets/tools/hetzner.jpg"
        subtitle: "Server Hosting"
        url: "https://console.hetzner.cloud"

      - name: "HostPoint"
        logo: "assets/tools/hostpoint.png"
        subtitle: "Domain Hosting"
        url: "https://admin.hostpoint.ch"

      - name: "Synology"
        logo: "assets/tools/synology.png"
        subtitle: "DiskStation"
        url: "https://cloud.larsgerber.ch/"

      - name: "Cloudinary"
        logo: "assets/tools/cloudinary.png"
        subtitle: "Content-Delivery-Network"
        url: "https://cloudinary.com/users/login"
        
      - name: "MongoDB"
        logo: "assets/tools/mongodb.svg"
        subtitle: "Database"
        url: "https://account.mongodb.com/account/login"

      - name: "Swisscom"
        logo: "assets/tools/swisscom.png"
        subtitle: "Router"
        url: "http://192.168.1.1/#overview"

  - name: "//Services"
    icon: "fab fa-docker"
    items:

      - name: "Traefik"
        logo: "assets/tools/traefik.png"
        subtitle: "Webserver"
        url: "https://infra-prd-web1.p.larsgerber.ch"
        
      - name: "Mailcow"
        logo: "assets/tools/mailcow.svg"
        subtitle: "Mailserver"
        url: "https://mail.larsgerber.ch/"

      - name: "Portainer"
        logo: "assets/tools/portainer.svg"
        subtitle: "Container Management"
        url: "https://portainer.larsgerber.ch"

      - name: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "Adblocker"
        url: "https://pihole.larsgerber.ch/"

      - name: "Bitwarden"
        logo: "assets/tools/bitwarden.png"
        subtitle: "Password Manager"
        url: "https://bitwarden.larsgerber.ch"

      # - name: "Grafana"
      #   logo: "assets/tools/grafana.png"
      #   subtitle: "Server Metrics"
      #   url: "https://metrics.larsgerber.ch"
        
      - name: "Umami"
        logo: "assets/tools/umami.png"
        subtitle: "Website Analytics"
        url: "https://analytics.larsgerber.ch"

      - name: "Etherpad"
        logo: "assets/tools/etherpad.svg"
        subtitle: "Online Editor"
        url: "https://etherpad.larsgerber.ch/"

  - name: "//Monitoring"
    icon: "fas fa-heartbeat"
    items:
      
      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.svg"
        subtitle: "Dashboard"
        url: "https://status.larsgerber.ch/dashboard"

      - name: "Uptime Kuma"
        logo: "assets/tools/uptime-kuma.svg"
        subtitle: "Status Page"
        url: "https://status.larsgerber.ch/status-page"

      - name: "Uptime Robot"
        logo: "assets/tools/uptime-robot.svg"
        subtitle: "Dashboard"
        url: "https://uptimerobot.com/login"

      - name: "Uptime Robot"
        logo: "assets/tools/uptime-robot.svg"
        subtitle: "Status Page"
        url: "https://stats.uptimerobot.com/3Y5j6Img8l"

  - name: "//Websites"
    icon: "fas fa-globe-europe"
    items:
      
      - name: "Swiss Gaming Clan"
        logo: "assets/tools/swissgamingclan.png"
        subtitle: "swissgamingclan.ch"
        url: "https://swissgamingclan.ch/"

      - name: "My link page"
        logo: "assets/tools/littlelink.png"
        subtitle: "larsgerber.ch"
        url: "https://larsgerber.ch/"

      - name: "My blog"
        logo: "assets/tools/lg.svg"
        subtitle: "blog.larsgerber.ch"
        url: "https://blog.larsgerber.ch/"

  - name: "//Applications"
    icon: "fas fa-cloud"
    items:

      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Media Server"
        url: "https://plex.larsgerber.ch"

      - name: "Strapi"
        logo: "assets/tools/strapi.svg"
        subtitle: "Content-Management-System"
        url: "https://strapi.larsgerber.ch/"
