---
services:
  homer:
    image: b4bz/homer:v24.11.5
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
