name: Docker CI

on: push

jobs:  
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1

    - name: Copy files to final destination
      run: |
        rm -rf /opt/homer
        mkdir /opt/homer
        cp -r * /opt/homer
